### ISSUE TITLE
How can I make this work quick on amazon aws?

### ISSUE THREAD

**Issue by pogilon** [hobu/greyhound#38]

**Comment by connormanning** [comment]
Install docker on an EC2 instance, write Entwine data to the local EBS volume or to S3 depending the size of your data, and then run Greyhound via Docker in EC2.  You'll need to be more specific beyond that - you'd run it the same way as you run locally, but in AWS's infrastructure.

**Comment by connormanning** [comment]
The Greyhound back-end serving [speck.ly](http://speck.ly) and [potree.entwine.io](http://potree.entwine.io) is a c3.2xlarge instance, by the way.  I recommend the c3 line of instances for Greyhound/Entwine stuff.

**Comment by pogilon** [comment]
@connormanning thank you, very useful :)
