### ISSUE TITLE
fatal error C1083: Cannot open include file: 'json/json.h': No such file or directory [C:\Users\user\Documents\Git\fork\greyhound\build\session.vcxproj

### ISSUE THREAD

**Issue by eric-schleicher** [hobu/greyhound#43]
Hello, 

Trying to get up and running with greyhound and running into this.  on the surface it looked like the much dreaded nodegyp rebuild problem that everyone just \*hates\* on windows...  but this looks a little different. citing a missing file.

`fatal error C1083: Cannot open include file: 'json/json.h': No such file or directory [C:\Users\user\Documents\Git\fork\greyhound\build\session.vcxproj]`

Not exactly sure where that json folder is supposed to live.

The combination of windows and nodegyp always seems touch and go, so not sure what's driving this issue.

Gist of the full console output
https://gist.github.com/eric-schleicher/645bdd1526c8aa9bbb5f0091cfe2cc1b

and a gist of the npm-debug.log
https://gist.github.com/eric-schleicher/895c9e5df272b0fa6281f28cc28c1dc4

let me know if it's something silly or simple.   This is from a freshly cloned  repo [30bba4613914463fae7f158a0de1ebb25213a375].  Other project on this system with nodegyp dependencies `npm install` just fine.

**Comment by connormanning** [comment]
I'm not sure where the JSON stuff should live on Windows - things are currently assumed to be Unix-based so I don't have any good advice.  You will probably need to modify the [bindings.gyp file](https://github.com/hobu/greyhound/blob/master/binding.gyp) with search paths for include/linking to match your JSON installation.
