### ISSUE TITLE
Cannot enlarge memory arrays. 

### ISSUE THREAD

**Issue by pogilon** [hobu/greyhound#45]
Hello @connormanning. With a new data, I am getting the following error in the browser coming from the greyhoundbinarydecoderworker.js. Any ideas what could it be or how to solve it? Thanks!

"Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 117440512, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs."

**Comment by pogilon** [comment]
Hello @connormanning. I just adjusted the TOTAL_MEMORY in the GreyhoundBinaryDecoderWorker.js" file. Could you please let me know what are the implications of increasing this value or what are those "some optimizations" that would be prevented if ALLOW_MEMORY_GROWTH is activated? Thanks!

**Comment by connormanning** [comment]
I don't know - you're talking about client settings of which I have little knowledge.  I've also never seen this error personally.  If you provide data I could try to recreate (in which case reopen this), but otherwise I have no ideas about this.
