### ISSUE TITLE
Filter argument sensative to quote type

### ISSUE THREAD

**Issue by Hisol** [hobu/greyhound#56]
I am passing a filter in the Greyhound query to select just a subset of point classifications.  If the URL is sent as

> &filter={'Classification': {'$in': [1, 2]}}

I get a 400 error

> Error during parsing: * Line 1, Column 21
>  Missing '}' or object member name

But if I change the quotes around the operator to double quotes, it is happy

> filter={"Classification": {"$in": [1, 2]}}

**Comment by connormanning** [comment]
The `filter` parameter must be valid JSON, which does require double quotes around strings.  This should probably be stated in the docs - will add.

**Comment by Hisol** [comment]
thanks for the update
