### ISSUE TITLE
Greyhound not reading entwine data

### ISSUE THREAD

**Issue by melezz** [hobu/greyhound#62]
Hello, 

I have a native installation of greyhound/entwine in Ubuntu 16.04 (current versions of entwine/grehound). I indexed a two different sets of data via entwine, and I get a crash each time I try to access them via potree/plas.io. The ubuntu is a virtual machine:

Using default config
Settings:
        Cache: 209715200 bytes
        Threads: 4
        Resource timeout: 30 minutes
        Tmp dir: /tmp
Paths:
        /greyhound
        ~/greyhound
        /entwine
        ~/entwine
        /opt/data
Headers:
        Access-Control-Allow-Methods: GET,PUT,POST,DELETE
        Access-Control-Allow-Origin: *
        Cache-Control: public, max-age=300
Writes NOT allowed
Static serve:
        /usr/local/include/greyhound/public
Listening:
        HTTP: 8080
Creating 1239
        Trying /greyhound: fail - Could not read file /greyhound/1239/entwine
        Trying ~/greyhound: Got error 11
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Abortado (`core' generado)
mariol@mario -VirtualBox:~$

It seems to find the dataset (it actually is in ~/greyhound/1239 but somehow it crashes...can anybody help out? 
thanks!

**Comment by melezz** [comment]
Sorry for the typo, here are the strikethrough lines:

Trying /greyhound: fail - Could not read file /greyhound/1239/entwine
        Trying ~/greyhound: Got error 11
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Abortado (`core' generado)

**Comment by connormanning** [comment]
Is this a very old index?  If so, could you try reindexing the data with entwine?  If not, can you post a link or email me the point cloud file that causes this issue.

**Comment by melezz** [comment]
Hello Connor, thanks a lot for the quick answer.
No, it's quite new, I used entwine for the indexing. I have the feeling that it is not a point cloud issue, I had exactly the same problem when I run the hello-world with red-rocks point cloud...Could it be an entwine/greyhound configuration problem? I installed it natively and I'm not quite sure that is working properly...I will post a link with the point cloud anyway as soon as I can

**Comment by connormanning** [comment]
I don't think it would be a configuration issue - looks like greyhound has no problem reading the file but doesn't like what's in it.  The only time I've seen that error is trying to read data indexed with pre-1.0 entwine.  You might try comparing your currently indexed output against that of the latest (or 1.2) entwine docker container and see if there's anything obviously different with the metadata.

**Comment by melezz** [comment]
Yes, you are right, greyhound looks ok. 
I am sure I am using entwine 1.2.0...I tried with the docker container and everything went right when indexing with the docker entwine engine as well.

It looks like I can't run greyhound with docker-compiled indexes or vicersa (i.e. point cloud indexed in docker and run with native greyhound installation)?  I get these:
- native entwine index + docker greyhound : " Trying /greyhound: fail - Laszip read failure: /greyhound/1239/5461.laz" -> native
- docker entwine index + native greyhound "Trying ~/greyhound: fail - The LAZ schema is not recognized"
May this be related?

Connor, where can I find the meta data files?

**Comment by connormanning** [comment]
The main metadata file is called simply `entwine` at the top level of the output.  What version is your PDAL build - presumably 1.6?

**Comment by melezz** [comment]
Thanks Connor, I will do the comparition
yes, PDAL is 1.6

**Comment by zhan520** [comment]
Can you solve it, if solved please let me know how to solve, I also in doing this, whatever you do I get 11 error
