### ISSUE TITLE
Greyhound server stops giving with error "Backtrace functionality was not linked" on AWS

### ISSUE THREAD

**Issue by bhavin266** [hobu/greyhound#66]
Hi,
I am running a greyhound server on AWS's m4.xlarge with entwine index hosted on s3 bucket. Have configured greyhound with cacheSize=2GB. The server keeps failing intermittently giving the following error.
Sweeping <RESOURCE_ID>...Got error 11
Backtrace functionality was not linked

 Currently I have only 3 resources indexed in s3. Below are the logs from couple of failures:

RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
Exception in pool task: Invalid lazperf chunk - no numPoints
Caught: Reservation failure
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
Sweeping RESOURCE_02... done
RESOURCE_1/info: 1 ms
Creating RESOURCE_02
        Trying s3://had-ape-entwine-demo/index: SUCCESS
RESOURCE_02/info: 1 ms
Sweeping RESOURCE_03...Got error 11
Backtrace functionality was not linked

----Restarted docker------------------------

HP: 21117 / 24576: 85.9253%
RESOURCE_2/hier: 0 ms D: [18, 25)
RESOURCE_2/read: 4 ms D: [19, 20) P: 76
RESOURCE_2/read: 9 ms D: [15, 16) P: 6955
RESOURCE_2/read: 4 ms D: [18, 19) P: 90
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
RESOURCE_1/info: 1 ms
Sweeping RESOURCE_03...Got error 11
Backtrace functionality was not linked

The only thing I could see common is that its failing while sweeping RESOURCE_03.
What could be the reason of this failure?

**Comment by connormanning** [comment]
Perhaps the invalid chunk above caused the issue - hard to say.  Either way, the new Entwine workflow (without Greyhound) is preferred: https://github.com/connormanning/entwine
