### ISSUE TITLE
I was set up test but I got the error

### ISSUE THREAD

**Issue by zhan520** [hobu/greyhound#67]
![image](https://user-images.githubusercontent.com/12770958/41963846-2a022b5a-7a2b-11e8-9840-876e7e409d7f.png)

**Comment by zhan520** [comment]
![image](https://user-images.githubusercontent.com/12770958/41456329-b166e2d4-70b2-11e8-8b0f-308ace3fb99f.png)
I have got some progress, and changed the version after got the error as shown in figure, I don't know what did I do wrong

**Comment by connormanning** [comment]
See updated readme: 36ffcf4a348312bd157b9d3e669fbf3e4acf7db6
