### ISSUE TITLE
greyhound cmake build fails with latest entwine

### ISSUE THREAD

**Issue by mangalbhaskar** [hobu/greyhound#68]
On Ubuntu 16.04 LTS and 18.04 LTS, I'm trying to spun the build with following in place:
- PDAL-1.7.1 - installed successfully
- entwine - latest git clone  - installed successfully
- greyhound - compilation errors

**Following is the error on using cmake build process:**
```c++
greyhound/greyhound/resource.cpp:9:10: fatal error: entwine/types/manifest.hpp: No such file or directory
 #include <entwine/types/manifest.hpp>
```
* If comments the above line, following error is thrown:
```c++
greyhound/greyhound/resource.cpp:13:10: fatal error: entwine/types/structure.hpp: No such file or directory
 #include <entwine/types/structure.hpp>
```
* If comments the above line also, lots of other errors thrown

I checked the latest entwine source, it does not have: `entwine/types/manifest.hpp` and `entwine/types/structure.hpp` files.

Seems the code is refactored as it has it in the previous builds under: `https://github.com/connormanning/entwine/tree/5c41466b0b62b4e39cb0c645b84ef379b1993a11/entwine/types`

**Questions:**
- which stable build/release of `entwine` should be used
- what are the plans on release to make greyhound latest code compatible with the latest stable release of entwine

**Comment by connormanning** [comment]
I've updated the Greyhound readme with the new workflow (which is: there is no Greyhound involved with the current Entwine workflow): 36ffcf4a348312bd157b9d3e669fbf3e4acf7db6
