### ISSUE TITLE
Trying /opt/data: fail - Could not read file /opt/data/PointCloud/entwine

### ISSUE THREAD

**Issue by swiss-knight** [hobu/greyhound#69]
When running greyhound with docker on Ubuntu I encountered some 'Could not read file' messages and nothing is displayed in the browser on the host machine. The most interesting of these messages is: 

`Trying /opt/data: fail - Could not read file /opt/data/PointCloud/entwine`

Here is the docker command used: 
`docker run --rm --name greyhound -it -v ${HOME}/data/entwine:/opt/data -p 8181:8080 connormanning/greyhound`

When I attach with a shell to this running greyhound server I can navigate to the `/opt/data/PointCloud` folder where, in addition to all the `*.laz` tiles, there is 3 files with the word 'entwine' in:
```
    entwine-build.json
    entwine-files.json
    entwine.json
```

I am trying to access the resources either through:    
http://speck.ly/?s=http://localhost:8181/&r=PointCloud
or:
http://potree.entwine.io/data/custom.html?s=localhost:8181/&r=PointCloud

Page is loading but content is empty (black background only).
I got a 403 error with potree viewer on the `entwine.json` file.
And a `The character encoding of the HTML document was not declared (...)` message with plasio + this: 
```
Unhandled promise rejection Error: "Failed to load resource config, server responded with:404"
thttp://speck.ly/js/plasio.js:82:13388rhttp://speck.ly/js/plasio.js:3:19424chttp://speck.ly/js/plasio.js:3:20546nhttp://speck.ly/js/plasio.js:3:19600rhttp://speck.ly/js/plasio.js:82:9366rhttp://speck.ly/js/plasio.js:82:9470ihttp://speck.ly/js/plasio.js:2:12259Ohttp://speck.ly/js/plasio.js:2:12404chttp://speck.ly/js/plasio.js:2:16497 plasio.js:2:12639
[Show/hide message details.] TypeError: F is undefined[Learn More] plasio-ui.js:61320:414
[Show/hide message details.] Error: Assert failed: (cursor? cursor)
```

**Comment by connormanning** [comment]
Please follow the instructions in [Entwine's readme](https://github.com/connormanning/entwine).  As mentioned in the "NOTE" section in this repository, Greyhound is not used in the visualization workflow.

**Comment by swiss-knight** [comment]
Thanks a lot connormanning!

Anyway, when trying with` http-server` it works, but only with potree. 
Plas.io (i.e. speck.ly) doesn't show up the cloud, it redirects to some remote data of NYC and complains not finding an `info` file.

So, if I understood;
- I must not use greyhoud anymore as a server,
- and I must only potree for visualizing a point cloud built with entwine.

**Comment by connormanning** [comment]
You can still use plasio - but it uses a new URL format for EPT data.  At the time that the readme was updated, plasio was not yet updated to this new format - I've added it to the readme instructions now.
