### ISSUE TITLE
Begining with greyhound 

### ISSUE THREAD

**Issue by pewixg3** [hobu/greyhound#73]
Hi

I need to set up a greyhound server but I do not know anything

is there a step-by-step tutorial?
Thank you

**Comment by hobu** [comment]
Greyhound is a project that is now considered in no-development maintenance mode. If you are just starting out and all you want to do is organize data for visualization and processing, [Entwine](https://entwine.io) and [Entwine Point Tile](https://entwine.io/entwine-point-tile.html) is sufficient by itself to do that task without Greyhound at all.
